nodeLinker: node-modules

npmScopes:
  messages:
    npmAlwaysAuth: true
    npmRegistryServer: "https://us-east1-npm.pkg.dev/triptease-guest-experience/messages-packages/"
  triptease-launchpad:
    npmAlwaysAuth: true
    npmRegistryServer: "https://us-east1-npm.pkg.dev/triptease-launchpad/launchpad-packages/"

packageExtensions:
  "@craftjs/utils@*":
    dependencies:
      react-dom: "*"
